/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrbanRouteImport } from './routes/urban'
import { Route as ScandinavianRouteImport } from './routes/scandinavian'
import { Route as LuxuryRouteImport } from './routes/luxury'
import { Route as IndexRouteImport } from './routes/index'

const UrbanRoute = UrbanRouteImport.update({
  id: '/urban',
  path: '/urban',
  getParentRoute: () => rootRouteImport,
} as any)
const ScandinavianRoute = ScandinavianRouteImport.update({
  id: '/scandinavian',
  path: '/scandinavian',
  getParentRoute: () => rootRouteImport,
} as any)
const LuxuryRoute = LuxuryRouteImport.update({
  id: '/luxury',
  path: '/luxury',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/luxury': typeof LuxuryRoute
  '/scandinavian': typeof ScandinavianRoute
  '/urban': typeof UrbanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/luxury': typeof LuxuryRoute
  '/scandinavian': typeof ScandinavianRoute
  '/urban': typeof UrbanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/luxury': typeof LuxuryRoute
  '/scandinavian': typeof ScandinavianRoute
  '/urban': typeof UrbanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/luxury' | '/scandinavian' | '/urban'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/luxury' | '/scandinavian' | '/urban'
  id: '__root__' | '/' | '/luxury' | '/scandinavian' | '/urban'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LuxuryRoute: typeof LuxuryRoute
  ScandinavianRoute: typeof ScandinavianRoute
  UrbanRoute: typeof UrbanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urban': {
      id: '/urban'
      path: '/urban'
      fullPath: '/urban'
      preLoaderRoute: typeof UrbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scandinavian': {
      id: '/scandinavian'
      path: '/scandinavian'
      fullPath: '/scandinavian'
      preLoaderRoute: typeof ScandinavianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luxury': {
      id: '/luxury'
      path: '/luxury'
      fullPath: '/luxury'
      preLoaderRoute: typeof LuxuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LuxuryRoute: LuxuryRoute,
  ScandinavianRoute: ScandinavianRoute,
  UrbanRoute: UrbanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
